### ISSUE TITLE
Terminal rewrite

### ISSUE THREAD

**Issue by Lordfirespeed** [lc-sigurd/Sigurd#18]
Planned for a week or so from now. 

### resources 
- https://wiki.ubuntu.com/CommandNotFoundMagic
- Express API 

### Todo 
- [ ] Implement middleware-based command runner 
  - [ ] 'states'
- [ ] Autocompletion providers
- [ ] Command history 
- [ ] Implement methods for creating and registering middleware-based commands 
- [ ] Implement methods for modifying the result of existing commands 
- [ ] re-implement all vanilla commands and states 
- [ ] disable (+ hook?) vanilla terminal methods
